# Site settings Update for my Blog : spaceg.github.io Do.9.April 15.49:24 2015 
title: Todd Stoffer
email: tdstoffe@ncsu.edu
description: "Hello, My Name is Todd Stoffer, I'm a librarian at NCSU Libraries"
baseurl: ""
url: "http://toddstoffer.com"
twitter_username: toddstoffer
github_username:  toddstoffer
google_username:  
instagram_username:  toddstoffer


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 5 #posts per page

